export const REQUEST_GET_POKEMON_WITH_TYPES = "REQUEST_GET_POKEMON_WITH_TYPES";
export const RECEIVE_GET_POKEMON_WITH_TYPES = "RECEIVE_GET_POKEMON_WITH_TYPES";
export const ERROR_GET_POKEMON_WITH_TYPES = "ERROR_GET_POKEMON_WITH_TYPES";
